### ISSUE TITLE
Extension stable-diffusion-webui-images-browser not work

### ISSUE THREAD

**Issue by wibus-wee** [wibus-wee/stable_diffusion_chilloutmix_ipynb#18]
### Describe the bug

```
You are running Gradio version 3.16.2. This version of the extension requires at least Gradio version 3.23.0.

For more details see https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/issues/116#issuecomment-1493259585
```

### Reproduction

Install extension and check the tab

### System Info

```Shell
python: 3.9.16  •  torch: 1.13.1+cu116  •  xformers: 0.0.16  •  gradio: 3.16.2  •  commit: 0cc0ee1b  •  checkpoint: fc2511737a
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SimonLiuGOAT** [comment]
Could you explain how to fix this bug?

**Comment by wibus-wee** [comment]
just upgrade Gradio version to 3.23.0 ~ *
